### ISSUE TITLE
Access denied

### ISSUE THREAD

**Issue by Codestech1** [hollow-cube/polar#13]
Just trying to convert anvil to polar. I have no idea what can cause that.

```
Exception in thread "main" java.io.IOException: Access denied
        at java.base/java.io.RandomAccessFile.write0(Native Method)
        at java.base/java.io.RandomAccessFile.write(RandomAccessFile.java:543)
        at java.base/java.io.RandomAccessFile.writeByte(RandomAccessFile.java:1086)
        at org.jglrxavpok.hephaistos.data.RandomAccessFileSource.writeByte(RandomAccessFileSource.kt)
        at org.jglrxavpok.hephaistos.mca.RegionFile.<init>(RegionFile.kt:61)
        at org.jglrxavpok.hephaistos.mca.RegionFile.<init>(RegionFile.kt:51)
        at org.jglrxavpok.hephaistos.mca.RegionFile.<init>(RegionFile.kt:50)
        at org.jglrxavpok.hephaistos.mca.RegionFile.<init>(RegionFile.kt)
        at net.hollowcube.polar.AnvilPolar.anvilToPolar(AnvilPolar.java:51)
        at org.hypejet.lobby.LobbyKt.main(Lobby.kt:23)
        at org.hypejet.lobby.LobbyKt.main(Lobby.kt)
```

**Comment by Codestech1** [comment]
Opened this world in minecraft 1.20.1 and then saved and tried to convert again, it worked, so i think it's because polar does not support 1.19.3 worlds
