### ISSUE TITLE
Doesn't work without using Minestom-CE

### ISSUE THREAD

**Issue by AstroSquared** [hollow-cube/polar#19]
When attempting to save chunks or unload the instance, this exception gets thrown:

```java
> java.lang.NoSuchMethodError: 'net.minestom.server.instance.light.Light net.minestom.server.instance.Section.blockLight()'
	at net.hollowcube.polar.PolarLoader.updateChunkData(PolarLoader.java:344)
	at net.hollowcube.polar.PolarLoader.lambda$saveChunks$3(PolarLoader.java:253)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at net.hollowcube.polar.PolarLoader.saveChunks(PolarLoader.java:253)
	at net.hollowcube.polar.PolarLoader.saveInstance(PolarLoader.java:240)
	at dev.bedcrab.server.PlayerLoader.unregisterInstance(PlayerLoader.java:77)
	at dev.bedcrab.events.PlayerEvents.onLeave(PlayerEvents.java:42)
	at net.minestom.server.event.EventListener$Builder$1.run(EventListener.java:151)
	at net.minestom.server.event.EventNodeImpl$Handle.callListener(EventNodeImpl.java:488)
	at net.minestom.server.event.EventNodeImpl$Handle.lambda$listenersConsumer$8(EventNodeImpl.java:420)
	at net.minestom.server.event.EventNodeImpl$Handle.lambda$createConsumer$5(EventNodeImpl.java:391)
	at net.minestom.server.event.EventNodeImpl$Handle.call(EventNodeImpl.java:324)
	at net.minestom.server.event.EventNode.call(EventNode.java:190)
	at net.minestom.server.event.EventDispatcher.call(EventDispatcher.java:10)
	at net.minestom.server.entity.Player.remove(Player.java:516)
	at net.minestom.server.entity.Entity.lambda$scheduleNextTick$1(Entity.java:219)
	at net.minestom.server.timer.Task$Builder$1.get(Task.java:68)
	at net.minestom.server.timer.Task$Builder$1.get(Task.java:59)
	at net.minestom.server.timer.SchedulerImpl.handleTask(SchedulerImpl.java:92)
	at net.minestom.server.timer.SchedulerImpl.lambda$processTick$3(SchedulerImpl.java:56)
	at org.jctools.queues.MessagePassingQueueUtil.drain(MessagePassingQueueUtil.java:39)
	at org.jctools.queues.BaseMpscLinkedArrayQueue.drain(BaseMpscLinkedArrayQueue.java:612)
	at org.jctools.queues.MpscUnboundedArrayQueue.drain(MpscUnboundedArrayQueue.java:23)
	at org.jctools.queues.MpscUnboundedArrayQueue.drain(MpscUnboundedArrayQueue.java:63)
	at net.minestom.server.timer.SchedulerImpl.processTick(SchedulerImpl.java:53)
	at net.minestom.server.timer.SchedulerImpl.processTick(SchedulerImpl.java:39)
	at net.minestom.server.entity.Entity.tick(Entity.java:527)
	at net.minestom.server.thread.TickThread.tick(TickThread.java:66)
	at net.minestom.server.thread.TickThread.run(TickThread.java:41)
```
I've noticed that it's calling `blockLight()` (doesn't exist) instead of `getBlockLight()` and the `Light` class doesn't exist.

**Comment by mworzala** [comment]
Yeah this is true, I did not properly test saving logic against base Minestom clearly. I am unsure if I will resolve this or just drop base Minestom support.

**Comment by mworzala** [comment]
CE will be merged back, so I will close this.
