### ISSUE TITLE
It seems everything is broken :(

### ISSUE THREAD

**Issue by MelonHell** [hollow-cube/polar#33]
https://github.com/Minestom/Minestom/commit/fb7e4b10e04b917cdf2207acd4aa4453145f75cc

Caused by: java.lang.NoSuchMethodError: 'java.util.List net.minestom.server.network.NetworkBuffer.readCollection(java.util.function.Function)'
	at net.hollowcube.polar.PolarReader.read(PolarReader.java:51)
	at net.hollowcube.polar.PolarLoader.<init>(PolarLoader.java:69)

**Comment by mworzala** [comment]
Fixed in #34
