### ISSUE TITLE
Standalone usage causes NoClassDefFoundError

### ISSUE THREAD

**Issue by TheDevMinerTV** [hollow-cube/polar#44]
When using polar standalone, it doesn't depend on Hephaistos and SLF4J through the Gradle.build* file. Any downstream user of Polar will encounter this error at runtime because Gradle isn't aware of these required libraries.

```
Exception in thread "main" java.lang.NoClassDefFoundError: org/jglrxavpok/hephaistos/mca/AnvilException
        at dev.csmc.polarconverter.Main.main(Main.java:32)
Caused by: java.lang.ClassNotFoundException: org.jglrxavpok.hephaistos.mca.AnvilException
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
        ... 1 more
```
```
Exception in thread "main" java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
        at net.hollowcube.polar.AnvilPolar.<clinit>(AnvilPolar.java:24)
        at dev.csmc.polarconverter.Main.main(Main.java:32)
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
        ... 2 more
```
```
Exception in thread "main" java.lang.NoClassDefFoundError: net/minestom/server/utils/chunk/ChunkUtils
        at net.hollowcube.polar.PolarWorld.<init>(PolarWorld.java:59)
        at net.hollowcube.polar.AnvilPolar.anvilToPolar(AnvilPolar.java:118)
        at net.hollowcube.polar.AnvilPolar.anvilToPolar(AnvilPolar.java:46)
        at dev.csmc.polarconverter.Main.main(Main.java:32)
Caused by: java.lang.ClassNotFoundException: net.minestom.server.utils.chunk.ChunkUtils
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
        ... 4 more
```
These libraries should be at least documented in the README or explicitly added to the gradle.build.kts.

**Comment by TheDevMinerTV** [comment]
Atleast document it please?
