### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by kopisa** [hollow-cube/polar#47]
Was checking if this would break easily so I set _couple_ random blocks around and 💥
```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 2048 out of bounds for length 1185
	at net.hollowcube.polar.PolarLoader.lambda$loadSection$0(PolarLoader.java:194)
	at net.minestom.server.instance.palette.FlexiblePalette.setAll(FlexiblePalette.java:123)
	at net.minestom.server.instance.palette.AdaptivePalette.setAll(AdaptivePalette.java:60)
	at net.hollowcube.polar.PolarLoader.loadSection(PolarLoader.java:192)
	at net.hollowcube.polar.PolarLoader.loadChunk(PolarLoader.java:154)
	at net.minestom.server.instance.InstanceContainer.lambda$retrieveChunk$7(InstanceContainer.java:305)
	at net.minestom.server.instance.InstanceContainer.retrieveChunk(InstanceContainer.java:333)
	at net.minestom.server.instance.InstanceContainer.lambda$loadChunk$1(InstanceContainer.java:252)
	at net.minestom.server.instance.InstanceContainer.loadOrRetrieve(InstanceContainer.java:672)
	at net.minestom.server.instance.InstanceContainer.loadChunk(InstanceContainer.java:252)
	at net.minestom.server.instance.InstanceContainer.setBlock(InstanceContainer.java:126)
	at net.minestom.server.instance.Instance.setBlock(Instance.java:175)
```
[world.zip](https://github.com/user-attachments/files/15848727/world.zip)

**Comment by kopisa** [comment]
looks like mismatch in blockData prepacked != unpacked

**Comment by kopisa** [comment]
fixed by changing
https://github.com/hollow-cube/polar/blob/main/src/main/java/net/hollowcube/polar/PolarReader.java#L132
to 
```java
var bitsPerEntry = (int) Math.ceil(Math.log(blockPalette.length) / Math.log(2));
```

🫡
