### ISSUE TITLE
Error when player join

### ISSUE THREAD

**Issue by EnterTG** [hollow-cube/polar#6]
Minestom: 9b15acf4fa
Polar: 1.1.1

When starting the server everything looks fine, only when the player tries to connect I get an error :(

```
lobbyWorldInstance = new InstanceContainer(UUID.randomUUID(), DimensionType.OVERWORLD);
PolarLoader polarLobbyLoader = new PolarLoader(Path.of(LOBBY_WORLD_PATH));

lobbyWorldInstance.setChunkLoader(polarMainLoader);
lobbyWorldInstance.getChunks()
	.forEach(chunk -> lobbyWorldInstance.loadChunk(chunk.getChunkX(), chunk.getChunkZ()));
```
```
Exception in thread "Ms-TickScheduler" java.lang.NoSuchMethodError: 'net.minestom.server.utils.chunk.ChunkSupplier net.minestom.server.instance.Instance.getChunkSupplier()'
        at Ext_myherolib//net.hollowcube.polar.compat.ChunkSupplierShim.lambda$select$0(ChunkSupplierShim.java:22)
        at Ext_myherolib//net.hollowcube.polar.PolarLoader.loadChunk(PolarLoader.java:82)
        at net.minestom.server.instance.InstanceContainer.lambda$retrieveChunk$8(InstanceContainer.java:266)
        at net.minestom.server.instance.InstanceContainer.retrieveChunk(InstanceContainer.java:292)
        at net.minestom.server.instance.InstanceContainer.lambda$loadOptionalChunk$4(InstanceContainer.java:218)
        at net.minestom.server.instance.InstanceContainer.loadOrRetrieve(InstanceContainer.java:630)
        at net.minestom.server.instance.InstanceContainer.loadOptionalChunk(InstanceContainer.java:218)
        at net.minestom.server.entity.Player.lambda$setInstance$9(Player.java:587)
        at net.minestom.server.utils.chunk.ChunkUtils.forChunksInRange(ChunkUtils.java:175)
        at net.minestom.server.utils.chunk.ChunkUtils.forChunksInRange(ChunkUtils.java:181)
        at net.minestom.server.entity.Player.setInstance(Player.java:586)
        at net.minestom.server.entity.Player.setInstance(Player.java:639)
        at net.minestom.server.entity.Player.UNSAFE_init(Player.java:331)
        at net.minestom.server.network.ConnectionManager.lambda$updateWaitingPlayers$5(ConnectionManager.java:266)
        at org.jctools.queues.MessagePassingQueueUtil.drain(MessagePassingQueueUtil.java:39)
        at org.jctools.queues.BaseMpscLinkedArrayQueue.drain(BaseMpscLinkedArrayQueue.java:612)
        at org.jctools.queues.MpscUnboundedArrayQueue.drain(MpscUnboundedArrayQueue.java:23)
        at org.jctools.queues.MpscUnboundedArrayQueue.drain(MpscUnboundedArrayQueue.java:63)
        at net.minestom.server.network.ConnectionManager.updateWaitingPlayers(ConnectionManager.java:256)
        at net.minestom.server.ServerProcessImpl$TickerImpl.tick(ServerProcessImpl.java:283)
        at net.minestom.server.thread.TickSchedulerThread.run(TickSchedulerThread.java:24)

```

**Comment by mworzala** [comment]
Fixed in https://github.com/hollow-cube/polar/releases/tag/1.1.2
